import PDFDocument from "pdfkit"

const COLORS = {
    title: '#111827',
    subtitle: '#6B7280',
    heading: '#1D4ED8',
    body: '#374151',
    rule: '#E5E7EB',
    footer: '#9CA3AF',
}

export const generatePDF = (data) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({
            size: "A4",
            margin: 50,
            // needed so we can go back and stamp a footer on every page
            // (including ones added automatically by text overflow) at the end
            bufferPages: true,
            info: {
                Author: 'Agent Space',
                Title: data.title ?? '',
                Creator: 'Agent Space'
            }
        })
        const chunks = [];
        doc.on('data', (chunk) => chunks.push(chunk))
        doc.on('end', () => resolve(Buffer.concat(chunks)))
        doc.on('error', (err) => reject(err))

        const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right

        // ---- Title ----
        doc
            .font('Helvetica-Bold')
            .fontSize(26)
            .fillColor(COLORS.title)
            .text(data.title ?? '', { align: 'center' })

        // ---- Subtitle ----
        if (data.subtitle) {
            doc.moveDown(0.4)
            doc
                .font('Helvetica')
                .fontSize(13)
                .fillColor(COLORS.subtitle)
                .text(data.subtitle, { align: 'center' })
        }

        // divider under the title block
        doc.moveDown(1)
        const ruleY = doc.y
        doc
            .strokeColor(COLORS.rule)
            .lineWidth(1)
            .moveTo(doc.page.margins.left, ruleY)
            .lineTo(doc.page.margins.left + pageWidth, ruleY)
            .stroke()

        doc.moveDown(1.5)

        // ---- Sections ----
        const sections = Array.isArray(data.sections) ? data.sections : []
        sections.forEach((section) => {
            doc
                .font('Helvetica-Bold')
                .fontSize(15)
                .fillColor(COLORS.heading)
                .text(section.heading ?? '', { align: 'left' })

            doc.moveDown(0.5)

            const points = Array.isArray(section.points) ? section.points : []
            points.forEach((point) => {
                doc
                    .font('Helvetica')
                    .fontSize(11.5)
                    .fillColor(COLORS.body)
                    .text(`•  ${point}`, {
                        align: 'left',
                        indent: 10,
                        lineGap: 4,
                    })
                doc.moveDown(0.3)
            })

            doc.moveDown(1)
        })

        const range = doc.bufferedPageRange()
        for (let i = range.start; i < range.start + range.count; i++) {
            doc.switchToPage(i)
            const bottom = doc.page.height - doc.page.margins.bottom + 15
            const originalBottomMargin = doc.page.margins.bottom
            doc.page.margins.bottom = 0

            doc
                .font('Helvetica')
                .fontSize(9)
                .fillColor(COLORS.footer)
                .text(
                    `Generated By Agent Space  •  Page ${i + 1} of ${range.count}`,
                    doc.page.margins.left,
                    bottom,
                    { align: 'center', width: pageWidth, lineBreak: false }
                )

            doc.page.margins.bottom = originalBottomMargin
        }

        doc.end()
    })
}